version: '2.3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  superset:
    container_name: superset
    build: .
    depends_on:
      - db
    init: true
    ports:
      - "8088:8088"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    platform: linux/x86_64
    volumes:
      - ./superset/superset_config_docker.py:/app/pythonpath/superset_config.py
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://superset:superset@db:5432/superset
      - SUPERSET_FEATURE_EMBEDDED_SUPERSET=true
