# reference
# - https://github.com/amancevice/docker-superset/blob/master/examples/postgres/docker-compose.yml

version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
  superset:
    build: ./superset
    depends_on:
      - postgres
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
  nginx:
    build: ./nginx
    ports:  
      - "8080:80"
    depends_on:
      - superset
volumes:
  postgres: